In [1]:
import pandas as pd

emaildata = pd.read_csv("spam_email_dataset.csv")
emaildata.shape

(10000, 20)

In [2]:
emaildata.head()

,email_id,subject,email_text,num_words,num_characters,num_exclamation_marks,num_links,has_suspicious_link,num_attachments,has_attachment,sender_email,sender_domain,sender_reputation_score,email_hour,email_day_of_week,is_weekend,num_recipients,contains_money_terms,contains_urgency_terms,label
0,0,Weekly Report,budget review - Statement our I claim world st...,19,114,0,2,0,2,1,lctvdzm@outlook.com,outlook.com,0.66,19,3,0,23,0,0,0
1,1,Project Update,team sync - President series today already. In...,18,114,0,7,0,0,0,pxyldmi@company.com,company.com,0.95,4,4,0,16,1,0,0
2,2,🔥WIN BIG NOW!!,win free urgent offer limited limited urgent u...,19,126,0,4,1,1,1,atvanls@unknownmail.cc,unknownmail.cc,0.68,3,0,0,10,1,1,1
3,3,🔥WIN BIG NOW!!,guarantee click now cash offer click now guara...,16,101,0,7,1,1,1,qalxcnf@chealdealz.xyz,chealdealz.xyz,0.69,19,5,1,25,1,1,1
4,4,Meeting Reminder,team sync - Significant property hotel not add...,18,111,0,7,1,2,1,xoiccxl@yahoo.com,yahoo.com,0.67,4,5,1,8,0,0,0

In [3]:
emaildata.describe()

,email_id,num_words,num_characters,num_exclamation_marks,num_links,has_suspicious_link,num_attachments,has_attachment,sender_reputation_score,email_hour,email_day_of_week,is_weekend,num_recipients,contains_money_terms,contains_urgency_terms,label
count,10000.00000,10000.000000,10000.000000,10000.0,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000
mean,4999.50000,18.097000,115.072400,0.0,3.976400,0.466700,0.803600,0.599600,0.681972,11.589600,3.00580,0.287100,15.501100,0.398500,0.499300,0.39950
std,2886.89568,5.163764,33.781247,0.0,2.580447,0.498915,0.752252,0.490004,0.172825,6.897023,2.00309,0.452431,8.650577,0.489614,0.500025,0.48982
min,0.00000,5.000000,25.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.300000,0.000000,0.00000,0.000000,1.000000,0.000000,0.000000,0.00000
25%,2499.75000,14.000000,91.000000,0.0,2.000000,0.000000,0.000000,0.000000,0.560000,6.000000,1.00000,0.000000,8.000000,0.000000,0.000000,0.00000
50%,4999.50000,18.000000,115.500000,0.0,4.000000,0.000000,1.000000,1.000000,0.690000,12.000000,3.00000,0.000000,16.000000,0.000000,0.000000,0.00000
75%,7499.25000,22.000000,139.000000,0.0,6.000000,1.000000,1.000000,1.000000,0.810000,18.000000,5.00000,1.000000,23.000000,1.000000,1.000000,1.00000
max,9999.00000,33.000000,221.000000,0.0,8.000000,1.000000,2.000000,1.000000,1.000000,23.000000,6.00000,1.000000,30.000000,1.000000,1.000000,1.00000

In [4]:
X_data = emaildata.drop("label", axis=1)
y_data = emaildata["label"]

X_data = pd.get_dummies(X_data)

In [5]:
X_data.head()

,email_id,num_words,num_characters,num_exclamation_marks,num_links,has_suspicious_link,num_attachments,has_attachment,sender_reputation_score,email_hour,...,sender_email_zzrecqf@yahoo.com,sender_email_zzrrzps@yahoo.com,sender_domain_chealdealz.xyz,sender_domain_company.com,sender_domain_freemoney.biz,sender_domain_gmail.com,sender_domain_outlook.com,sender_domain_unknownmail.cc,sender_domain_winbignow.ru,sender_domain_yahoo.com
0,0,19,114,0,2,0,2,1,0.66,19,...,0,0,0,0,0,0,1,0,0,0
1,1,18,114,0,7,0,0,0,0.95,4,...,0,0,0,1,0,0,0,0,0,0
2,2,19,126,0,4,1,1,1,0.68,3,...,0,0,0,0,0,0,0,1,0,0
3,3,16,101,0,7,1,1,1,0.69,19,...,0,0,1,0,0,0,0,0,0,0
4,4,18,111,0,7,1,2,1,0.67,4,...,0,0,0,0,0,0,0,0,0,1

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_data, y_data, test_size=0.2, random_state=42)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(8000, 20031)
(2000, 20031)
(8000,)
(2000,)

In [8]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
import tensorflow as tf
from tensorflow import keras

model = keras.Sequential()
model.add(keras.layers.Dense(40, activation="relu", input_shape=X_train.shape[1:]))
model.add(keras.layers.Dense(30, activation="relu"))
model.add(keras.layers.Dense(1, activation="sigmoid"))

In [23]:
model.compile(loss="binary_crossentropy", optimizer="sgd", metrics=["accuracy"])

In [24]:
history = model.fit(X_train, y_train, epochs=10, validation_data=(X_test, y_test))

Epoch 1/10
250/250 [==============================] - 3s 11ms/step - loss: 0.6001 - accuracy: 0.6802 - val_loss: 0.4356 - val_accuracy: 0.9980
Epoch 2/10
250/250 [==============================] - 1s 5ms/step - loss: 0.1531 - accuracy: 0.9799 - val_loss: 0.2144 - val_accuracy: 0.9970
Epoch 3/10
250/250 [==============================] - 1s 5ms/step - loss: 0.0364 - accuracy: 0.9984 - val_loss: 0.1480 - val_accuracy: 0.9975
Epoch 4/10
250/250 [==============================] - 1s 5ms/step - loss: 0.0159 - accuracy: 0.9996 - val_loss: 0.1191 - val_accuracy: 0.9980
Epoch 5/10
250/250 [==============================] - 1s 5ms/step - loss: 0.0095 - accuracy: 0.9999 - val_loss: 0.1027 - val_accuracy: 0.9980
Epoch 6/10
250/250 [==============================] - 1s 5ms/step - loss: 0.0066 - accuracy: 0.9999 - val_loss: 0.0918 - val_accuracy: 0.9980
Epoch 7/10
250/250 [==============================] - 1s 5ms/step - loss: 0.0050 - accuracy: 0.9999 - val_loss: 0.0840 - val_accuracy: 0.9980
Epoch 8/10
250/250 [==============================] - 1s 5ms/step - loss: 0.0040 - accuracy: 0.9999 - val_loss: 0.0781 - val_accuracy: 0.9980
Epoch 9/10
250/250 [==============================] - 1s 5ms/step - loss: 0.0033 - accuracy: 1.0000 - val_loss: 0.0734 - val_accuracy: 0.9980
Epoch 10/10
250/250 [==============================] - 1s 5ms/step - loss: 0.0028 - accuracy: 1.0000 - val_loss: 0.0696 - val_accuracy: 0.9980

In [25]:
model.evaluate(X_test, y_test)

63/63 [==============================] - 0s 4ms/step - loss: 0.0696 - accuracy: 0.9980

[0.06960079073905945, 0.9980000257492065]

In [27]:
4+4

8